### PR TITLE
remove template literal to be es5 compliant

### PR DESCRIPTION
**Pull request by TimBest**

### CODE REVIEW

**Comment by tigt** [comment]
Yeah, okay. I don't know why that's important but I trust there's some reason.

**Comment by Gyllsdorff** [comment]
@tigt 
From the README.md
> Internet Explorer 9 and up, including Edge

Template strings are not supported by IE.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Browser_compatibility

**Comment by tigt** [comment]
@Gyllsdorff: Ah, I had meant that the generated SVG output `data:` URI works in those browsers, not the JS itself. I should make that clearer.

**Comment by Gyllsdorff** [comment]
Ah, I see.

The company I work at have this embedded in the browser js bundle so this line stops us from supporting IE11. Of course we can add a babel transpilation step for this dependency or fork it and fix it ourselves but it would be much better (for us 😄) if this PR could be merged and released.

**Comment by Gyllsdorff** [comment]
@tigt 
Is there anything I can do to help this get merged and released?

**Comment by tigt** [comment]
@Gyllsdorff That ping was sufficient, I just needed to remember when I was on my laptop.

Should be published as 1.0.2, but let me know if I did something wrong.

**Comment by Gyllsdorff** [comment]
Thank you, great work. 👍  

The release is npm (https://www.npmjs.com/package/mini-svg-data-uri) now. It is not visible in the web UI yet but if you go to https://www.npmjs.com/package/mini-svg-data-uri/v/1.0.2 you can see it.

**Pull request merged**
