### PR TITLE
Add typescript types

### PR DESCRIPTION
**Pull request by fjc0k**
This is a great package, but the typescript types is missing. Therefore, I made this PR.

image

image

### CODE REVIEW

**Comment by tigt** [comment]
I’m not against merging this in. However, because I don’t personally use TypeScript, I may do a bad job…

- Updating for new TS features/versions/etc.
- Helping consumers with TS problems
- I might even break the types for any future refactors or features, despite trying not to

Is that okay with you?

**Comment by fjc0k** [comment]
@tigt Of course, I will keep the types in sync with the usage and deal with the problems encountered by typescript users.  🤝 🤓

**Comment by tigt** [comment]
Sounds good to me. I added you as a collaborator to the repo — does that let you merge it in yourself?

**Comment by fjc0k** [comment]
@tigt thx,  can you publish it to npm?  😁

**Comment by tigt** [comment]
Yep, as soon as I remember how. On it.

**Comment by tigt** [comment]
I _think_ I did it right — let me know if `1.2.3` works for you.

**Comment by fjc0k** [comment]
@tigt yes, it works!  🍻

image

image

**Pull request merged**
